func_mapping = {
'<osl type 1>':'import os',
'<osl sys>':'os.system',
'<osl rem>':'os.remove',
'<osl ren>':'os.rename',
'<osl altsep <cap>>':'os.altsep.capitalize',
'<osl altsep <cou>>':'os.altsep.count',
'<osl altsep <cen>>':'os.altsep.center',
'<osl altsep <cas>>':'os.altsep.casefold',
'<osl altsep <class>>':'os.altsep.__class__',
'<osl altsep <con>>':'os.altsep.__contains__',
'<osl altsep <doc>>':'os.altsep.__doc__',
'<osl altsep <dict>>':'os.altsep.__dict__',
'<osl altsep <dir>>':'os.altsep.__dir__',
'<osl altsep <dela>>':'os.altsep.__delattr__',
'<osl altsep <encode>>':'os.altsep.encode',
'<osl altsep <endswith>>':'os.altsep.endswith',
'<osl altsep <expandtabs>>':'os.altsep.expandtabs',
'<osl altsep <find>>':'os.altsep.find',
'<osl altsep <format>>':'os.altsep.format',
'<osl altsep <format_M>>':'os.altsep.format_map',
'<osl altsep <__format__>>':'os.altsep.__format__',
'<osl altsep <__ge__>>':'os.altsep.__ge__',
'<osl altsep <__gt__>>':'os.altsep.__gt__',
'<osl altsep <__getitem__>>':'os.altsep.__getitem__',
'<osl altsep <geta>>':'os.altsep.__getattribute__',
'<osl altsep <hash>':'os.altsep.__hash__',
'<osl altsep <isalnum>>':'os.altsep.isalnum',
'<osl altsep <isascii>>':'os.altsep.isascii',
'<osl altsep <index>>':'os.altsep.index',
'<osl altsep <isalpha>>':'os.altsep.isalpha',
'<osl altsep <isdigit>>':'os.altsep.isdecimal',
'<osl altsep <isidentifier>>':'os.altsep.isidentifier',
'<osl altsep <oslower>>':'os.altsep.islower',
'<osl altsep <isnumeric>>':'os.altsep.isnumeric',
'<osl altsep <isprintable>>':'os.altsep.isprintable',
'<osl altsep <isspace>>':'os.altsep.isspace',
'<osl altsep <istitle>>':'os.altsep.istitle',
'<osl altsep <isupper>>':'os.altsep.isupper',
'<osl altsep <join>>':'os.altsep.join',
'<osl altsep <ljust>>':'os.altsep.ljust',
'<osl altsep <lower>>':'os.altsep.lower',
'<osl altsep <lstrip>>':'os.altsep.lstrip',
'<osl altsep <mt>>':'os.altsep.maketrans',
'<osl altsep <partition>>':'os.altsep.partition',
'<osl altsep <rindex>>':'os.altsep.rindex',
'<osl altsep <rsplit>>':'os.altsep.rsplit',
'<osl altsep <removeprefix>>':'os.altsep.removeprefix',
'<osl altsep <removesuffix>>':'os.altsep.removesuffix',
'<osl altsep <replace>>':'os.altsep.replace',
'<osl altsep <rpartition>>':'os.altsep.rpartition',
'<osl altsep <__reduce__>>':'os.altsep.__reduce__',
'<osl altsep <__reduce_ex__>>':'os.altsep.__reduce_ex__',
'<osl altsep <__reversed__>>':'os.altsep.__reversed__',
'<osl altsep <__repr__>>':'os.altsep.__repr__',
'<osl altsep <__rmul__>>':'os.altsep.__rmul__',
'<osl altsep <split>>':'os.altsep.split',
'<osl altsep <strip>>':'os.altsep.strip',
'<osl altsep <swapcase>>':'os.altsep.swapcase',
'<osl altsep <startswith>>':'os.altsep.startswith',
'<osl altsep <splitlines>>':'os.altsep.splitlines',
'<osl altsep <__setattr__>>':'os.altsep.__setattr__',
'<osl altsep <__sizeof__>>':'os.altsep.__sizeof__',
'<osl altsep <__slots__>>':'os.altsep.__slots__',
'<osl altsep <__str__>>':'os.altsep.__str__',
'<osl altsep <title>>':'os.altsep.title',
'<osl altsep <translate>>':'os.altsep.translate',
'<osl altsep <upper>>':'os.altsep.upper',
'<osl altsep <zfill>>':'os.altsep.zfill',
'<osl altsep <rfind>>':'os.altsep.rfind',
'<osl altsep <rjust>>':'os.altsep.rjust',
'<osl altsep <:main_class:>>':'os.altsep',
'<osl abort>':'os.abort',
'<osl access>':'os.access',
'<osl ad3>':'os.add_dll_directory',
'<osl close>':'os.close',
'<osl chdir>':'os.chdir',
'<osl chmod>':'os.chmod',
'<osl chown>':'os.chown',
'<osl chroot>':'os.chroot',
'<osl confstr>':'os.confstr',
'<osl chflags>':'os.chflags',
'<osl copy_file_range>':'os.copy_file_range',
'<osl cpu_count>':'os.cpu_count',
'<osl ctermid>':'os.ctermid',
'<osl curdir>':'os.curdir',
'<osl confstr_names>':'os.confstr_names',
'<osl curdir <cap>>':'os.curdir.capitalize',
'<osl curdir <cou>>':'os.curdir.count',
'<osl curdir <cen>>':'os.curdir.center',
'<osl curdir <cas>>':'os.curdir.casefold',
'<osl curdir <class>>':'os.curdir.__class__',
'<osl curdir <con>>':'os.curdir.__contains__',
'<osl curdir <doc>>':'os.curdir.__doc__',
'<osl curdir <dict>>':'os.curdir.__dict__',
'<osl curdir <dir>>':'os.curdir.__dir__',
'<osl curdir <dela>>':'os.curdir.__delattr__',
'<osl curdir <encode>>':'os.curdir.encode',
'<osl curdir <endswith>>':'os.curdir.endswith',
'<osl curdir <expandtabs>>':'os.curdir.expandtabs',
'<osl curdir <find>>':'os.curdir.find',
'<osl curdir <format>>':'os.curdir.format',
'<osl curdir <format_M>>':'os.curdir.format_map',
'<osl curdir <__format__>>':'os.curdir.__format__',
'<osl curdir <__ge__>>':'os.curdir.__ge__',
'<osl curdir <__gt__>>':'os.curdir.__gt__',
'<osl curdir <__getitem__>>':'os.curdir.__getitem__',
'<osl curdir <geta>>':'os.curdir.__getattribute__',
'<osl curdir <hash>':'os.curdir.__hash__',
'<osl curdir <isalnum>>':'os.curdir.isalnum',
'<osl curdir <isascii>>':'os.curdir.isascii',
'<osl curdir <index>>':'os.curdir.index',
'<osl curdir <isalpha>>':'os.curdir.isalpha',
'<osl curdir <isdigit>>':'os.curdir.isdecimal',
'<osl curdir <isidentifier>>':'os.curdir.isidentifier',
'<osl curdir <oslower>>':'os.curdir.islower',
'<osl curdir <isnumeric>>':'os.curdir.isnumeric',
'<osl curdir <isprintable>>':'os.curdir.isprintable',
'<osl curdir <isspace>>':'os.curdir.isspace',
'<osl curdir <istitle>>':'os.curdir.istitle',
'<osl curdir <isupper>>':'os.curdir.isupper',
'<osl curdir <join>>':'os.curdir.join',
'<osl curdir <ljust>>':'os.curdir.ljust',
'<osl curdir <lower>>':'os.curdir.lower',
'<osl curdir <lstrip>>':'os.curdir.lstrip',
'<osl curdir <mt>>':'os.curdir.maketrans',
'<osl curdir <partition>>':'os.curdir.partition',
'<osl curdir <rindex>>':'os.curdir.rindex',
'<osl curdir <rsplit>>':'os.curdir.rsplit',
'<osl curdir <removeprefix>>':'os.curdir.removeprefix',
'<osl curdir <removesuffix>>':'os.curdir.removesuffix',
'<osl curdir <replace>>':'os.curdir.replace',
'<osl curdir <rpartition>>':'os.curdir.rpartition',
'<osl curdir <__reduce__>>':'os.curdir.__reduce__',
'<osl curdir <__reduce_ex__>>':'os.curdir.__reduce_ex__',
'<osl curdir <__reversed__>>':'os.curdir.__reversed__',
'<osl curdir <__repr__>>':'os.curdir.__repr__',
'<osl curdir <__rmul__>>':'os.curdir.__rmul__',
'<osl curdir <split>>':'os.curdir.split',
'<osl curdir <strip>>':'os.curdir.strip',
'<osl curdir <swapcase>>':'os.curdir.swapcase',
'<osl curdir <startswith>>':'os.curdir.startswith',
'<osl curdir <splitlines>>':'os.curdir.splitlines',
'<osl curdir <__setattr__>>':'os.curdir.__setattr__',
'<osl curdir <__sizeof__>>':'os.curdir.__sizeof__',
'<osl curdir <__slots__>>':'os.curdir.__slots__',
'<osl curdir <__str__>>':'os.curdir.__str__',
'<osl curdir <title>>':'os.curdir.title',
'<osl curdir <translate>>':'os.curdir.translate',
'<osl curdir <upper>>':'os.curdir.upper',
'<osl curdir <zfill>>':'os.curdir.zfill',
'<osl curdir <rfind>>':'os.curdir.rfind',
'<osl curdir <rjust>>':'os.curdir.rjust',
'<osl curdir <:main_class:>>':'os.curdir',
'<osl devnull <cap>>':'os.devnull.capitalize',
'<osl devnull <cou>>':'os.devnull.count',
'<osl devnull <cen>>':'os.devnull.center',
'<osl devnull <cas>>':'os.devnull.casefold',
'<osl devnull <class>>':'os.devnull.__class__',
'<osl devnull <con>>':'os.devnull.__contains__',
'<osl devnull <doc>>':'os.devnull.__doc__',
'<osl devnull <dict>>':'os.devnull.__dict__',
'<osl devnull <dir>>':'os.devnull.__dir__',
'<osl devnull <dela>>':'os.devnull.__delattr__',
'<osl devnull <encode>>':'os.devnull.encode',
'<osl devnull <endswith>>':'os.devnull.endswith',
'<osl devnull <expandtabs>>':'os.devnull.expandtabs',
'<osl devnull <find>>':'os.devnull.find',
'<osl devnull <format>>':'os.devnull.format',
'<osl devnull <format_M>>':'os.devnull.format_map',
'<osl devnull <__format__>>':'os.devnull.__format__',
'<osl devnull <__ge__>>':'os.devnull.__ge__',
'<osl devnull <__gt__>>':'os.devnull.__gt__',
'<osl devnull <__getitem__>>':'os.devnull.__getitem__',
'<osl devnull <geta>>':'os.devnull.__getattribute__',
'<osl devnull <hash>':'os.devnull.__hash__',
'<osl devnull <isalnum>>':'os.devnull.isalnum',
'<osl devnull <isascii>>':'os.devnull.isascii',
'<osl devnull <index>>':'os.devnull.index',
'<osl devnull <isalpha>>':'os.devnull.isalpha',
'<osl devnull <isdigit>>':'os.devnull.isdecimal',
'<osl devnull <isidentifier>>':'os.devnull.isidentifier',
'<osl devnull <oslower>>':'os.devnull.islower',
'<osl devnull <isnumeric>>':'os.devnull.isnumeric',
'<osl devnull <isprintable>>':'os.devnull.isprintable',
'<osl devnull <isspace>>':'os.devnull.isspace',
'<osl devnull <istitle>>':'os.devnull.istitle',
'<osl devnull <isupper>>':'os.devnull.isupper',
'<osl devnull <join>>':'os.devnull.join',
'<osl devnull <ljust>>':'os.devnull.ljust',
'<osl devnull <lower>>':'os.devnull.lower',
'<osl devnull <lstrip>>':'os.devnull.lstrip',
'<osl devnull <mt>>':'os.devnull.maketrans',
'<osl devnull <partition>>':'os.devnull.partition',
'<osl devnull <rindex>>':'os.devnull.rindex',
'<osl devnull <rsplit>>':'os.devnull.rsplit',
'<osl devnull <removeprefix>>':'os.devnull.removeprefix',
'<osl devnull <removesuffix>>':'os.devnull.removesuffix',
'<osl devnull <replace>>':'os.devnull.replace',
'<osl devnull <rpartition>>':'os.devnull.rpartition',
'<osl devnull <__reduce__>>':'os.devnull.__reduce__',
'<osl devnull <__reduce_ex__>>':'os.devnull.__reduce_ex__',
'<osl devnull <__reversed__>>':'os.devnull.__reversed__',
'<osl devnull <__repr__>>':'os.devnull.__repr__',
'<osl devnull <__rmul__>>':'os.devnull.__rmul__',
'<osl devnull <split>>':'os.devnull.split',
'<osl devnull <strip>>':'os.devnull.strip',
'<osl devnull <swapcase>>':'os.devnull.swapcase',
'<osl devnull <startswith>>':'os.devnull.startswith',
'<osl devnull <splitlines>>':'os.devnull.splitlines',
'<osl devnull <__setattr__>>':'os.devnull.__setattr__',
'<osl devnull <__sizeof__>>':'os.devnull.__sizeof__',
'<osl devnull <__slots__>>':'os.devnull.__slots__',
'<osl devnull <__str__>>':'os.devnull.__str__',
'<osl devnull <title>>':'os.devnull.title',
'<osl devnull <translate>>':'os.devnull.translate',
'<osl devnull <upper>>':'os.devnull.upper',
'<osl devnull <zfill>>':'os.devnull.zfill',
'<osl devnull <rfind>>':'os.devnull.rfind',
'<osl devnull <rjust>>':'os.devnull.rjust',
'<osl devnull <:main_class:>>':'os.devnull',
'<osl defpath <cap>>':'os.defpath.capitalize',
'<osl defpath <cou>>':'os.defpath.count',
'<osl defpath <cen>>':'os.defpath.center',
'<osl defpath <cas>>':'os.defpath.casefold',
'<osl defpath <class>>':'os.defpath.__class__',
'<osl defpath <con>>':'os.defpath.__contains__',
'<osl defpath <doc>>':'os.defpath.__doc__',
'<osl defpath <dict>>':'os.defpath.__dict__',
'<osl defpath <dir>>':'os.defpath.__dir__',
'<osl defpath <dela>>':'os.defpath.__delattr__',
'<osl defpath <encode>>':'os.defpath.encode',
'<osl defpath <endswith>>':'os.defpath.endswith',
'<osl defpath <expandtabs>>':'os.defpath.expandtabs',
'<osl defpath <find>>':'os.defpath.find',
'<osl defpath <format>>':'os.defpath.format',
'<osl defpath <format_M>>':'os.defpath.format_map',
'<osl defpath <__format__>>':'os.defpath.__format__',
'<osl defpath <__ge__>>':'os.defpath.__ge__',
'<osl defpath <__gt__>>':'os.defpath.__gt__',
'<osl defpath <__getitem__>>':'os.defpath.__getitem__',
'<osl defpath <geta>>':'os.defpath.__getattribute__',
'<osl defpath <hash>':'os.defpath.__hash__',
'<osl defpath <isalnum>>':'os.defpath.isalnum',
'<osl defpath <isascii>>':'os.defpath.isascii',
'<osl defpath <index>>':'os.defpath.index',
'<osl defpath <isalpha>>':'os.defpath.isalpha',
'<osl defpath <isdigit>>':'os.defpath.isdecimal',
'<osl defpath <isidentifier>>':'os.defpath.isidentifier',
'<osl defpath <oslower>>':'os.defpath.islower',
'<osl defpath <isnumeric>>':'os.defpath.isnumeric',
'<osl defpath <isprintable>>':'os.defpath.isprintable',
'<osl defpath <isspace>>':'os.defpath.isspace',
'<osl defpath <istitle>>':'os.defpath.istitle',
'<osl defpath <isupper>>':'os.defpath.isupper',
'<osl defpath <join>>':'os.defpath.join',
'<osl defpath <ljust>>':'os.defpath.ljust',
'<osl defpath <lower>>':'os.defpath.lower',
'<osl defpath <lstrip>>':'os.defpath.lstrip',
'<osl defpath <mt>>':'os.defpath.maketrans',
'<osl defpath <partition>>':'os.defpath.partition',
'<osl defpath <rindex>>':'os.defpath.rindex',
'<osl defpath <rsplit>>':'os.defpath.rsplit',
'<osl defpath <removeprefix>>':'os.defpath.removeprefix',
'<osl defpath <removesuffix>>':'os.defpath.removesuffix',
'<osl defpath <replace>>':'os.defpath.replace',
'<osl defpath <rpartition>>':'os.defpath.rpartition',
'<osl defpath <__reduce__>>':'os.defpath.__reduce__',
'<osl defpath <__reduce_ex__>>':'os.defpath.__reduce_ex__',
'<osl defpath <__reversed__>>':'os.defpath.__reversed__',
'<osl defpath <__repr__>>':'os.defpath.__repr__',
'<osl defpath <__rmul__>>':'os.defpath.__rmul__',
'<osl defpath <split>>':'os.defpath.split',
'<osl defpath <strip>>':'os.defpath.strip',
'<osl defpath <swapcase>>':'os.defpath.swapcase',
'<osl defpath <startswith>>':'os.defpath.startswith',
'<osl defpath <splitlines>>':'os.defpath.splitlines',
'<osl defpath <__setattr__>>':'os.defpath.__setattr__',
'<osl defpath <__sizeof__>>':'os.defpath.__sizeof__',
'<osl defpath <__slots__>>':'os.defpath.__slots__',
'<osl defpath <__str__>>':'os.defpath.__str__',
'<osl defpath <title>>':'os.defpath.title',
'<osl defpath <translate>>':'os.defpath.translate',
'<osl defpath <upper>>':'os.defpath.upper',
'<osl defpath <zfill>>':'os.defpath.zfill',
'<osl defpath <rfind>>':'os.defpath.rfind',
'<osl defpath <rjust>>':'os.defpath.rjust',
'<osl defpath <:main_class:>>':'os.defpath',
'<osl device_encoding>':'os.device_encoding',
'<osl error>':'os.error',
'<osl extsep <cap>>':'os.extsep.capitalize',
'<osl extsep <cou>>':'os.extsep.count',
'<osl extsep <cen>>':'os.extsep.center',
'<osl extsep <cas>>':'os.extsep.casefold',
'<osl extsep <class>>':'os.extsep.__class__',
'<osl extsep <con>>':'os.extsep.__contains__',
'<osl extsep <doc>>':'os.extsep.__doc__',
'<osl extsep <dict>>':'os.extsep.__dict__',
'<osl extsep <dir>>':'os.extsep.__dir__',
'<osl extsep <dela>>':'os.extsep.__delattr__',
'<osl extsep <encode>>':'os.extsep.encode',
'<osl extsep <endswith>>':'os.extsep.endswith',
'<osl extsep <expandtabs>>':'os.extsep.expandtabs',
'<osl extsep <find>>':'os.extsep.find',
'<osl extsep <format>>':'os.extsep.format',
'<osl extsep <format_M>>':'os.extsep.format_map',
'<osl extsep <__format__>>':'os.extsep.__format__',
'<osl extsep <__ge__>>':'os.extsep.__ge__',
'<osl extsep <__gt__>>':'os.extsep.__gt__',
'<osl extsep <__getitem__>>':'os.extsep.__getitem__',
'<osl extsep <geta>>':'os.extsep.__getattribute__',
'<osl extsep <hash>':'os.extsep.__hash__',
'<osl extsep <isalnum>>':'os.extsep.isalnum',
'<osl extsep <isascii>>':'os.extsep.isascii',
'<osl extsep <index>>':'os.extsep.index',
'<osl extsep <isalpha>>':'os.extsep.isalpha',
'<osl extsep <isdigit>>':'os.extsep.isdecimal',
'<osl extsep <isidentifier>>':'os.extsep.isidentifier',
'<osl extsep <oslower>>':'os.extsep.islower',
'<osl extsep <isnumeric>>':'os.extsep.isnumeric',
'<osl extsep <isprintable>>':'os.extsep.isprintable',
'<osl extsep <isspace>>':'os.extsep.isspace',
'<osl extsep <istitle>>':'os.extsep.istitle',
'<osl extsep <isupper>>':'os.extsep.isupper',
'<osl extsep <join>>':'os.extsep.join',
'<osl extsep <ljust>>':'os.extsep.ljust',
'<osl extsep <lower>>':'os.extsep.lower',
'<osl extsep <lstrip>>':'os.extsep.lstrip',
'<osl extsep <mt>>':'os.extsep.maketrans',
'<osl extsep <partition>>':'os.extsep.partition',
'<osl extsep <rindex>>':'os.extsep.rindex',
'<osl extsep <rsplit>>':'os.extsep.rsplit',
'<osl extsep <removeprefix>>':'os.extsep.removeprefix',
'<osl extsep <removesuffix>>':'os.extsep.removesuffix',
'<osl extsep <replace>>':'os.extsep.replace',
'<osl extsep <rpartition>>':'os.extsep.rpartition',
'<osl extsep <__reduce__>>':'os.extsep.__reduce__',
'<osl extsep <__reduce_ex__>>':'os.extsep.__reduce_ex__',
'<osl extsep <__reversed__>>':'os.extsep.__reversed__',
'<osl extsep <__repr__>>':'os.extsep.__repr__',
'<osl extsep <__rmul__>>':'os.extsep.__rmul__',
'<osl extsep <split>>':'os.extsep.split',
'<osl extsep <strip>>':'os.extsep.strip',
'<osl extsep <swapcase>>':'os.extsep.swapcase',
'<osl extsep <startswith>>':'os.extsep.startswith',
'<osl extsep <splitlines>>':'os.extsep.splitlines',
'<osl extsep <__setattr__>>':'os.extsep.__setattr__',
'<osl extsep <__sizeof__>>':'os.extsep.__sizeof__',
'<osl extsep <__slots__>>':'os.extsep.__slots__',
'<osl extsep <__str__>>':'os.extsep.__str__',
'<osl extsep <title>>':'os.extsep.title',
'<osl extsep <translate>>':'os.extsep.translate',
'<osl extsep <upper>>':'os.extsep.upper',
'<osl extsep <zfill>>':'os.extsep.zfill',
'<osl extsep <rfind>>':'os.extsep.rfind',
'<osl extsep <rjust>>':'os.extsep.rjust',
'<osl extsep <:main_class:>>':'os.extsep',
'<osl fchdir>':'os.fchdir',
'<osl fchmod>':'os.fchmod',
'<osl fchown>':'os.fchown',
'<osl fdopen>':'os.fdopen',
'<osl fdatasync>':'os.fdatasync',
'<osl fork>':'os.fork',
'<osl fpathconf>':'os.fpathconf',
'<osl forkpty>':'os.forkpty',
'<osl fstat>':'os.fstat',
'<osl fsync>':'os.fsync',
'<osl fspath>':'os.fspath',
'<osl fsdecode>':'os.fsdecode',
'<osl fsencode>':'os.fsencode',
'<osl fstatvfs>':'os.fstatvfs',
'<osl ftruncate>':'os.ftruncate',
'<osl fwalk>':'os.fwalk',
'<osl getcwd>':'os.getcwd',
'<osl getenv>':'os.getenv',
'<osl getgid>':'os.getgid',
'<osl get_blocking>':'os.get_blocking',
'<osl get_exec_path>':'os.get_exec_path',
'<osl get_handle_inheritable>':'os.get_handle_inheritable',
'<osl get_inheritable>':'os.get_inheritable',
'<osl get_terminal_size>':'os.get_terminal_size',
'<osl getcwdb>':'os.getcwdb',
'<osl getegid>':'os.getegid',
'<osl getenvb>':'os.getenvb',
'<osl geteuid>':'os.geteuid',
'<osl getgrouplist>':'os.getgrouplist',
'<osl getgroups>':'os.getgroups',
'<osl getloadavg>':'os.getloadavg',
'<osl getlogin>':'os.getlogin',
'<osl getpgrp>':'os.getpgrp',
'<osl getpid>':'os.getpid',
'<osl getppid>':'os.getppid',
'<osl getpriority>':'os.getpriority',
'<osl getpgid>':'os.getpgid',
'<osl getrandom>':'os.getrandom',
'<osl getresgid>':'os.getresgid',
'<osl getresuid>':'os.getresuid',
'<osl getsid>':'os.getsid',
'<osl getuid>':'os.getuid',
'<osl getxattr>':'os.getxattr',
'<osl isatty>':'os.isatty',
'<osl initgroups>':'os.initgroups',
'<osl kill>':'os.kill',
'<osl killpg>':'os.killpg',
'<osl lchown>':'os.lchown',
'<osl lchflags>':'os.lchflags',
'<osl link>':'os.link',
'<osl linesep>':'os.linesep',
'<osl listdir>':'os.listdir',
'<osl listxattr>':'os.listxattr',
'<osl lockf>':'os.lockf',
'<osl login_tty>':'os.login_tty',
'<osl lseek>':'os.lseek',
'<osl lstat>':'os.lstat',
'<osl name <cap>>':'os.name.capitalize',
'<osl name <cou>>':'os.name.count',
'<osl name <cen>>':'os.name.center',
'<osl name <cas>>':'os.name.casefold',
'<osl name <class>>':'os.name.__class__',
'<osl name <con>>':'os.name.__contains__',
'<osl name <doc>>':'os.name.__doc__',
'<osl name <dict>>':'os.name.__dict__',
'<osl name <dir>>':'os.name.__dir__',
'<osl name <dela>>':'os.name.__delattr__',
'<osl name <encode>>':'os.name.encode',
'<osl name <endswith>>':'os.name.endswith',
'<osl name <expandtabs>>':'os.name.expandtabs',
'<osl name <find>>':'os.name.find',
'<osl name <format>>':'os.name.format',
'<osl name <format_M>>':'os.name.format_map',
'<osl name <__format__>>':'os.name.__format__',
'<osl name <__ge__>>':'os.name.__ge__',
'<osl name <__gt__>>':'os.name.__gt__',
'<osl name <__getitem__>>':'os.name.__getitem__',
'<osl name <geta>>':'os.name.__getattribute__',
'<osl name <hash>':'os.name.__hash__',
'<osl name <isalnum>>':'os.name.isalnum',
'<osl name <isascii>>':'os.name.isascii',
'<osl name <index>>':'os.name.index',
'<osl name <isalpha>>':'os.name.isalpha',
'<osl name <isdigit>>':'os.name.isdecimal',
'<osl name <isidentifier>>':'os.name.isidentifier',
'<osl name <oslower>>':'os.name.islower',
'<osl name <isnumeric>>':'os.name.isnumeric',
'<osl name <isprintable>>':'os.name.isprintable',
'<osl name <isspace>>':'os.name.isspace',
'<osl name <istitle>>':'os.name.istitle',
'<osl name <isupper>>':'os.name.isupper',
'<osl name <join>>':'os.name.join',
'<osl name <ljust>>':'os.name.ljust',
'<osl name <lower>>':'os.name.lower',
'<osl name <lstrip>>':'os.name.lstrip',
'<osl name <mt>>':'os.name.maketrans',
'<osl name <partition>>':'os.name.partition',
'<osl name <rindex>>':'os.name.rindex',
'<osl name <rsplit>>':'os.name.rsplit',
'<osl name <removeprefix>>':'os.name.removeprefix',
'<osl name <removesuffix>>':'os.name.removesuffix',
'<osl name <replace>>':'os.name.replace',
'<osl name <rpartition>>':'os.name.rpartition',
'<osl name <__reduce__>>':'os.name.__reduce__',
'<osl name <__reduce_ex__>>':'os.name.__reduce_ex__',
'<osl name <__reversed__>>':'os.name.__reversed__',
'<osl name <__repr__>>':'os.name.__repr__',
'<osl name <__rmul__>>':'os.name.__rmul__',
'<osl name <split>>':'os.name.split',
'<osl name <strip>>':'os.name.strip',
'<osl name <swapcase>>':'os.name.swapcase',
'<osl name <startswith>>':'os.name.startswith',
'<osl name <splitlines>>':'os.name.splitlines',
'<osl name <__setattr__>>':'os.name.__setattr__',
'<osl name <__sizeof__>>':'os.name.__sizeof__',
'<osl name <__slots__>>':'os.name.__slots__',
'<osl name <__str__>>':'os.name.__str__',
'<osl name <title>>':'os.name.title',
'<osl name <translate>>':'os.name.translate',
'<osl name <upper>>':'os.name.upper',
'<osl name <zfill>>':'os.name.zfill',
'<osl name <rfind>>':'os.name.rfind',
'<osl name <rjust>>':'os.name.rjust',
'<osl name <:main_class:>>':'os.name',
'<osl nice>':'os.nice',
'<osl mkdir>':'os.mkdir',
'<osl major>':'os.major',
'<osl minor>':'os.minor',
'<osl mknod>':'os.mknod',
'<osl makedev>':'os.makedev',
'<osl makedirs>':'os.makedirs',
'<osl mkfifo>':'os.mkfifo',
'<osl memfd_create>':'os.memfd_create',
'<osl open>':'os.open',
'<osl openpty>':'os.openpty',
'<osl path <altsep>>':'os.path.altsep',
'<osl path <abspath>>':'os.path.abspath',
'<osl path <basename>>':'os.path.basename',
'<osl path <curdir>>':'os.path.curdir',
'<osl path <commonpath>>':'os.path.commonpath',
'<osl path <commonprefix>>':'os.path.commonprefix',
'<osl path <defpath>>':'os.path.defpath',
'<osl path.devnull <cap>>':'os.path.devnull.capitalize',
'<osl path.devnull <cou>>':'os.path.devnull.count',
'<osl path.devnull <cen>>':'os.path.devnull.center',
'<osl path.devnull <cas>>':'os.path.devnull.casefold',
'<osl path.devnull <class>>':'os.path.devnull.__class__',
'<osl path.devnull <con>>':'os.path.devnull.__contains__',
'<osl path.devnull <doc>>':'os.path.devnull.__doc__',
'<osl path.devnull <dict>>':'os.path.devnull.__dict__',
'<osl path.devnull <dir>>':'os.path.devnull.__dir__',
'<osl path.devnull <dela>>':'os.path.devnull.__delattr__',
'<osl path.devnull <encode>>':'os.path.devnull.encode',
'<osl path.devnull <endswith>>':'os.path.devnull.endswith',
'<osl path.devnull <expandtabs>>':'os.path.devnull.expandtabs',
'<osl path.devnull <find>>':'os.path.devnull.find',
'<osl path.devnull <format>>':'os.path.devnull.format',
'<osl path.devnull <format_M>>':'os.path.devnull.format_map',
'<osl path.devnull <__format__>>':'os.path.devnull.__format__',
'<osl path.devnull <__ge__>>':'os.path.devnull.__ge__',
'<osl path.devnull <__gt__>>':'os.path.devnull.__gt__',
'<osl path.devnull <__getitem__>>':'os.path.devnull.__getitem__',
'<osl path.devnull <geta>>':'os.path.devnull.__getattribute__',
'<osl path.devnull <hash>':'os.path.devnull.__hash__',
'<osl path.devnull <isalnum>>':'os.path.devnull.isalnum',
'<osl path.devnull <isascii>>':'os.path.devnull.isascii',
'<osl path.devnull <index>>':'os.path.devnull.index',
'<osl path.devnull <isalpha>>':'os.path.devnull.isalpha',
'<osl path.devnull <isdigit>>':'os.path.devnull.isdecimal',
'<osl path.devnull <isidentifier>>':'os.path.devnull.isidentifier',
'<osl path.devnull <oslower>>':'os.path.devnull.islower',
'<osl path.devnull <isnumeric>>':'os.path.devnull.isnumeric',
'<osl path.devnull <isprintable>>':'os.path.devnull.isprintable',
'<osl path.devnull <isspace>>':'os.path.devnull.isspace',
'<osl path.devnull <istitle>>':'os.path.devnull.istitle',
'<osl path.devnull <isupper>>':'os.path.devnull.isupper',
'<osl path.devnull <join>>':'os.path.devnull.join',
'<osl path.devnull <ljust>>':'os.path.devnull.ljust',
'<osl path.devnull <lower>>':'os.path.devnull.lower',
'<osl path.devnull <lstrip>>':'os.path.devnull.lstrip',
'<osl path.devnull <mt>>':'os.path.devnull.maketrans',
'<osl path.devnull <partition>>':'os.path.devnull.partition',
'<osl path.devnull <rindex>>':'os.path.devnull.rindex',
'<osl path.devnull <rsplit>>':'os.path.devnull.rsplit',
'<osl path.devnull <removeprefix>>':'os.path.devnull.removeprefix',
'<osl path.devnull <removesuffix>>':'os.path.devnull.removesuffix',
'<osl path.devnull <replace>>':'os.path.devnull.replace',
'<osl path.devnull <rpartition>>':'os.path.devnull.rpartition',
'<osl path.devnull <__reduce__>>':'os.path.devnull.__reduce__',
'<osl path.devnull <__reduce_ex__>>':'os.path.devnull.__reduce_ex__',
'<osl path.devnull <__reversed__>>':'os.path.devnull.__reversed__',
'<osl path.devnull <__repr__>>':'os.path.devnull.__repr__',
'<osl path.devnull <__rmul__>>':'os.path.devnull.__rmul__',
'<osl path.devnull <split>>':'os.path.devnull.split',
'<osl path.devnull <strip>>':'os.path.devnull.strip',
'<osl path.devnull <swapcase>>':'os.path.devnull.swapcase',
'<osl path.devnull <startswith>>':'os.path.devnull.startswith',
'<osl path.devnull <splitlines>>':'os.path.devnull.splitlines',
'<osl path.devnull <__setattr__>>':'os.path.devnull.__setattr__',
'<osl path.devnull <__sizeof__>>':'os.path.devnull.__sizeof__',
'<osl path.devnull <__slots__>>':'os.path.devnull.__slots__',
'<osl path.devnull <__str__>>':'os.path.devnull.__str__',
'<osl path.devnull <title>>':'os.path.devnull.title',
'<osl path.devnull <translate>>':'os.path.devnull.translate',
'<osl path.devnull <upper>>':'os.path.devnull.upper',
'<osl path.devnull <zfill>>':'os.path.devnull.zfill',
'<osl path.devnull <rfind>>':'os.path.devnull.rfind',
'<osl path.devnull <rjust>>':'os.path.devnull.rjust',
'<osl path.devnull <:main_class:>>':'os.path.devnull',
'<osl path <dirname>>':'os.path.dirname',
'<osl path.extsep <cap>>':'os.path.extsep.capitalize',
'<osl path.extsep <cou>>':'os.path.extsep.count',
'<osl path.extsep <cen>>':'os.path.extsep.center',
'<osl path.extsep <cas>>':'os.path.extsep.casefold',
'<osl path.extsep <class>>':'os.path.extsep.__class__',
'<osl path.extsep <con>>':'os.path.extsep.__contains__',
'<osl path.extsep <doc>>':'os.path.extsep.__doc__',
'<osl path.extsep <dict>>':'os.path.extsep.__dict__',
'<osl path.extsep <dir>>':'os.path.extsep.__dir__',
'<osl path.extsep <dela>>':'os.path.extsep.__delattr__',
'<osl path.extsep <encode>>':'os.path.extsep.encode',
'<osl path.extsep <endswith>>':'os.path.extsep.endswith',
'<osl path.extsep <expandtabs>>':'os.path.extsep.expandtabs',
'<osl path.extsep <find>>':'os.path.extsep.find',
'<osl path.extsep <format>>':'os.path.extsep.format',
'<osl path.extsep <format_M>>':'os.path.extsep.format_map',
'<osl path.extsep <__format__>>':'os.path.extsep.__format__',
'<osl path.extsep <__ge__>>':'os.path.extsep.__ge__',
'<osl path.extsep <__gt__>>':'os.path.extsep.__gt__',
'<osl path.extsep <__getitem__>>':'os.path.extsep.__getitem__',
'<osl path.extsep <geta>>':'os.path.extsep.__getattribute__',
'<osl path.extsep <hash>':'os.path.extsep.__hash__',
'<osl path.extsep <isalnum>>':'os.path.extsep.isalnum',
'<osl path.extsep <isascii>>':'os.path.extsep.isascii',
'<osl path.extsep <index>>':'os.path.extsep.index',
'<osl path.extsep <isalpha>>':'os.path.extsep.isalpha',
'<osl path.extsep <isdigit>>':'os.path.extsep.isdecimal',
'<osl path.extsep <isidentifier>>':'os.path.extsep.isidentifier',
'<osl path.extsep <oslower>>':'os.path.extsep.islower',
'<osl path.extsep <isnumeric>>':'os.path.extsep.isnumeric',
'<osl path.extsep <isprintable>>':'os.path.extsep.isprintable',
'<osl path.extsep <isspace>>':'os.path.extsep.isspace',
'<osl path.extsep <istitle>>':'os.path.extsep.istitle',
'<osl path.extsep <isupper>>':'os.path.extsep.isupper',
'<osl path.extsep <join>>':'os.path.extsep.join',
'<osl path.extsep <ljust>>':'os.path.extsep.ljust',
'<osl path.extsep <lower>>':'os.path.extsep.lower',
'<osl path.extsep <lstrip>>':'os.path.extsep.lstrip',
'<osl path.extsep <mt>>':'os.path.extsep.maketrans',
'<osl path.extsep <partition>>':'os.path.extsep.partition',
'<osl path.extsep <rindex>>':'os.path.extsep.rindex',
'<osl path.extsep <rsplit>>':'os.path.extsep.rsplit',
'<osl path.extsep <removeprefix>>':'os.path.extsep.removeprefix',
'<osl path.extsep <removesuffix>>':'os.path.extsep.removesuffix',
'<osl path.extsep <replace>>':'os.path.extsep.replace',
'<osl path.extsep <rpartition>>':'os.path.extsep.rpartition',
'<osl path.extsep <__reduce__>>':'os.path.extsep.__reduce__',
'<osl path.extsep <__reduce_ex__>>':'os.path.extsep.__reduce_ex__',
'<osl path.extsep <__reversed__>>':'os.path.extsep.__reversed__',
'<osl path.extsep <__repr__>>':'os.path.extsep.__repr__',
'<osl path.extsep <__rmul__>>':'os.path.extsep.__rmul__',
'<osl path.extsep <split>>':'os.path.extsep.split',
'<osl path.extsep <strip>>':'os.path.extsep.strip',
'<osl path.extsep <swapcase>>':'os.path.extsep.swapcase',
'<osl path.extsep <startswith>>':'os.path.extsep.startswith',
'<osl path.extsep <splitlines>>':'os.path.extsep.splitlines',
'<osl path.extsep <__setattr__>>':'os.path.extsep.__setattr__',
'<osl path.extsep <__sizeof__>>':'os.path.extsep.__sizeof__',
'<osl path.extsep <__slots__>>':'os.path.extsep.__slots__',
'<osl path.extsep <__str__>>':'os.path.extsep.__str__',
'<osl path.extsep <title>>':'os.path.extsep.title',
'<osl path.extsep <translate>>':'os.path.extsep.translate',
'<osl path.extsep <upper>>':'os.path.extsep.upper',
'<osl path.extsep <zfill>>':'os.path.extsep.zfill',
'<osl path.extsep <rfind>>':'os.path.extsep.rfind',
'<osl path.extsep <rjust>>':'os.path.extsep.rjust',
'<osl path.extsep <:main_class:>>':'os.path.extsep',
'<osl path <exists>>':'os.path.exists',
'<osl path <expanduser>>':'os.path.expanduser',
'<osl path <expandvars>>':'os.path.expandvars',
'<osl path <getsize>>':'os.path.getsize',
'<osl path <getmtime>>':'os.path.getmtime',
'<osl path <getatime>>':'os.path.getatime',
'<osl path <getctime>>':'os.path.getctime',
'<osl path <isdir>>':'os.path.isdir',
'<osl path <isabs>>':'os.path.isabs',
'<osl path <isfile>>':'os.path.isfile',
'<osl path <islink>>':'os.path.islink',
'<osl path <ismount>>':'os.path.ismount',
'<osl path <join>>':'os.path.join',
'<osl path <lexists>>':'os.path.lexists',
'<osl path <normcase>>':'os.path.normcase',
'<osl path.pardir <cap>>':'os.path.pardir.capitalize',
'<osl path.pardir <cou>>':'os.path.pardir.count',
'<osl path.pardir <cen>>':'os.path.pardir.center',
'<osl path.pardir <cas>>':'os.path.pardir.casefold',
'<osl path.pardir <class>>':'os.path.pardir.__class__',
'<osl path.pardir <con>>':'os.path.pardir.__contains__',
'<osl path.pardir <doc>>':'os.path.pardir.__doc__',
'<osl path.pardir <dict>>':'os.path.pardir.__dict__',
'<osl path.pardir <dir>>':'os.path.pardir.__dir__',
'<osl path.pardir <dela>>':'os.path.pardir.__delattr__',
'<osl path.pardir <encode>>':'os.path.pardir.encode',
'<osl path.pardir <endswith>>':'os.path.pardir.endswith',
'<osl path.pardir <expandtabs>>':'os.path.pardir.expandtabs',
'<osl path.pardir <find>>':'os.path.pardir.find',
'<osl path.pardir <format>>':'os.path.pardir.format',
'<osl path.pardir <format_M>>':'os.path.pardir.format_map',
'<osl path.pardir <__format__>>':'os.path.pardir.__format__',
'<osl path.pardir <__ge__>>':'os.path.pardir.__ge__',
'<osl path.pardir <__gt__>>':'os.path.pardir.__gt__',
'<osl path.pardir <__getitem__>>':'os.path.pardir.__getitem__',
'<osl path.pardir <geta>>':'os.path.pardir.__getattribute__',
'<osl path.pardir <hash>':'os.path.pardir.__hash__',
'<osl path.pardir <isalnum>>':'os.path.pardir.isalnum',
'<osl path.pardir <isascii>>':'os.path.pardir.isascii',
'<osl path.pardir <index>>':'os.path.pardir.index',
'<osl path.pardir <isalpha>>':'os.path.pardir.isalpha',
'<osl path.pardir <isdigit>>':'os.path.pardir.isdecimal',
'<osl path.pardir <isidentifier>>':'os.path.pardir.isidentifier',
'<osl path.pardir <oslower>>':'os.path.pardir.islower',
'<osl path.pardir <isnumeric>>':'os.path.pardir.isnumeric',
'<osl path.pardir <isprintable>>':'os.path.pardir.isprintable',
'<osl path.pardir <isspace>>':'os.path.pardir.isspace',
'<osl path.pardir <istitle>>':'os.path.pardir.istitle',
'<osl path.pardir <isupper>>':'os.path.pardir.isupper',
'<osl path.pardir <join>>':'os.path.pardir.join',
'<osl path.pardir <ljust>>':'os.path.pardir.ljust',
'<osl path.pardir <lower>>':'os.path.pardir.lower',
'<osl path.pardir <lstrip>>':'os.path.pardir.lstrip',
'<osl path.pardir <mt>>':'os.path.pardir.maketrans',
'<osl path.pardir <partition>>':'os.path.pardir.partition',
'<osl path.pardir <rindex>>':'os.path.pardir.rindex',
'<osl path.pardir <rsplit>>':'os.path.pardir.rsplit',
'<osl path.pardir <removeprefix>>':'os.path.pardir.removeprefix',
'<osl path.pardir <removesuffix>>':'os.path.pardir.removesuffix',
'<osl path.pardir <replace>>':'os.path.pardir.replace',
'<osl path.pardir <rpartition>>':'os.path.pardir.rpartition',
'<osl path.pardir <__reduce__>>':'os.path.pardir.__reduce__',
'<osl path.pardir <__reduce_ex__>>':'os.path.pardir.__reduce_ex__',
'<osl path.pardir <__reversed__>>':'os.path.pardir.__reversed__',
'<osl path.pardir <__repr__>>':'os.path.pardir.__repr__',
'<osl path.pardir <__rmul__>>':'os.path.pardir.__rmul__',
'<osl path.pardir <split>>':'os.path.pardir.split',
'<osl path.pardir <strip>>':'os.path.pardir.strip',
'<osl path.pardir <swapcase>>':'os.path.pardir.swapcase',
'<osl path.pardir <startswith>>':'os.path.pardir.startswith',
'<osl path.pardir <splitlines>>':'os.path.pardir.splitlines',
'<osl path.pardir <__setattr__>>':'os.path.pardir.__setattr__',
'<osl path.pardir <__sizeof__>>':'os.path.pardir.__sizeof__',
'<osl path.pardir <__slots__>>':'os.path.pardir.__slots__',
'<osl path.pardir <__str__>>':'os.path.pardir.__str__',
'<osl path.pardir <title>>':'os.path.pardir.title',
'<osl path.pardir <translate>>':'os.path.pardir.translate',
'<osl path.pardir <upper>>':'os.path.pardir.upper',
'<osl path.pardir <zfill>>':'os.path.pardir.zfill',
'<osl path.pardir <rfind>>':'os.path.pardir.rfind',
'<osl path.pardir <rjust>>':'os.path.pardir.rjust',
'<osl path.pardir <:main_class:>>':'os.path.pardir',
'<osl path <pathsep>>':'os.path.pathsep',
'<osl path <realpath>>':'os.path.realpath',
'<osl path <relpath>>':'os.path.relpath',
'<osl path <split>>':'os.path.split',
'<osl path <splitext>>':'os.path.splitext',
'<osl path.sep <cap>>':'os.path.sep.capitalize',
'<osl path.sep <cou>>':'os.path.sep.count',
'<osl path.sep <cen>>':'os.path.sep.center',
'<osl path.sep <cas>>':'os.path.sep.casefold',
'<osl path.sep <class>>':'os.path.sep.__class__',
'<osl path.sep <con>>':'os.path.sep.__contains__',
'<osl path.sep <doc>>':'os.path.sep.__doc__',
'<osl path.sep <dict>>':'os.path.sep.__dict__',
'<osl path.sep <dir>>':'os.path.sep.__dir__',
'<osl path.sep <dela>>':'os.path.sep.__delattr__',
'<osl path.sep <encode>>':'os.path.sep.encode',
'<osl path.sep <endswith>>':'os.path.sep.endswith',
'<osl path.sep <expandtabs>>':'os.path.sep.expandtabs',
'<osl path.sep <find>>':'os.path.sep.find',
'<osl path.sep <format>>':'os.path.sep.format',
'<osl path.sep <format_M>>':'os.path.sep.format_map',
'<osl path.sep <__format__>>':'os.path.sep.__format__',
'<osl path.sep <__ge__>>':'os.path.sep.__ge__',
'<osl path.sep <__gt__>>':'os.path.sep.__gt__',
'<osl path.sep <__getitem__>>':'os.path.sep.__getitem__',
'<osl path.sep <geta>>':'os.path.sep.__getattribute__',
'<osl path.sep <hash>':'os.path.sep.__hash__',
'<osl path.sep <isalnum>>':'os.path.sep.isalnum',
'<osl path.sep <isascii>>':'os.path.sep.isascii',
'<osl path.sep <index>>':'os.path.sep.index',
'<osl path.sep <isalpha>>':'os.path.sep.isalpha',
'<osl path.sep <isdigit>>':'os.path.sep.isdecimal',
'<osl path.sep <isidentifier>>':'os.path.sep.isidentifier',
'<osl path.sep <oslower>>':'os.path.sep.islower',
'<osl path.sep <isnumeric>>':'os.path.sep.isnumeric',
'<osl path.sep <isprintable>>':'os.path.sep.isprintable',
'<osl path.sep <isspace>>':'os.path.sep.isspace',
'<osl path.sep <istitle>>':'os.path.sep.istitle',
'<osl path.sep <isupper>>':'os.path.sep.isupper',
'<osl path.sep <join>>':'os.path.sep.join',
'<osl path.sep <ljust>>':'os.path.sep.ljust',
'<osl path.sep <lower>>':'os.path.sep.lower',
'<osl path.sep <lstrip>>':'os.path.sep.lstrip',
'<osl path.sep <mt>>':'os.path.sep.maketrans',
'<osl path.sep <partition>>':'os.path.sep.partition',
'<osl path.sep <rindex>>':'os.path.sep.rindex',
'<osl path.sep <rsplit>>':'os.path.sep.rsplit',
'<osl path.sep <removeprefix>>':'os.path.sep.removeprefix',
'<osl path.sep <removesuffix>>':'os.path.sep.removesuffix',
'<osl path.sep <replace>>':'os.path.sep.replace',
'<osl path.sep <rpartition>>':'os.path.sep.rpartition',
'<osl path.sep <__reduce__>>':'os.path.sep.__reduce__',
'<osl path.sep <__reduce_ex__>>':'os.path.sep.__reduce_ex__',
'<osl path.sep <__reversed__>>':'os.path.sep.__reversed__',
'<osl path.sep <__repr__>>':'os.path.sep.__repr__',
'<osl path.sep <__rmul__>>':'os.path.sep.__rmul__',
'<osl path.sep <split>>':'os.path.sep.split',
'<osl path.sep <strip>>':'os.path.sep.strip',
'<osl path.sep <swapcase>>':'os.path.sep.swapcase',
'<osl path.sep <startswith>>':'os.path.sep.startswith',
'<osl path.sep <splitlines>>':'os.path.sep.splitlines',
'<osl path.sep <__setattr__>>':'os.path.sep.__setattr__',
'<osl path.sep <__sizeof__>>':'os.path.sep.__sizeof__',
'<osl path.sep <__slots__>>':'os.path.sep.__slots__',
'<osl path.sep <__str__>>':'os.path.sep.__str__',
'<osl path.sep <title>>':'os.path.sep.title',
'<osl path.sep <translate>>':'os.path.sep.translate',
'<osl path.sep <upper>>':'os.path.sep.upper',
'<osl path.sep <zfill>>':'os.path.sep.zfill',
'<osl path.sep <rfind>>':'os.path.sep.rfind',
'<osl path.sep <rjust>>':'os.path.sep.rjust',
'<osl path.sep <:main_class:>>':'os.path.sep',
'<osl path <samefile>>':'os.path.samefile',
'<osl path <samestat>>':'os.path.samestat',
'<osl path <sameopenfile>>':'os.path.sameopenfile',
'<osl path <splitdrive>>':'os.path.splitdrive',
'<osl path <supports_unicode_filenames>>':'os.path.supports_unicode_filenames',
'<osl pathsep <cap>>':'os.pathsep.capitalize',
'<osl pathsep <cou>>':'os.pathsep.count',
'<osl pathsep <cen>>':'os.pathsep.center',
'<osl pathsep <cas>>':'os.pathsep.casefold',
'<osl pathsep <class>>':'os.pathsep.__class__',
'<osl pathsep <con>>':'os.pathsep.__contains__',
'<osl pathsep <doc>>':'os.pathsep.__doc__',
'<osl pathsep <dict>>':'os.pathsep.__dict__',
'<osl pathsep <dir>>':'os.pathsep.__dir__',
'<osl pathsep <dela>>':'os.pathsep.__delattr__',
'<osl pathsep <encode>>':'os.pathsep.encode',
'<osl pathsep <endswith>>':'os.pathsep.endswith',
'<osl pathsep <expandtabs>>':'os.pathsep.expandtabs',
'<osl pathsep <find>>':'os.pathsep.find',
'<osl pathsep <format>>':'os.pathsep.format',
'<osl pathsep <format_M>>':'os.pathsep.format_map',
'<osl pathsep <__format__>>':'os.pathsep.__format__',
'<osl pathsep <__ge__>>':'os.pathsep.__ge__',
'<osl pathsep <__gt__>>':'os.pathsep.__gt__',
'<osl pathsep <__getitem__>>':'os.pathsep.__getitem__',
'<osl pathsep <geta>>':'os.pathsep.__getattribute__',
'<osl pathsep <hash>':'os.pathsep.__hash__',
'<osl pathsep <isalnum>>':'os.pathsep.isalnum',
'<osl pathsep <isascii>>':'os.pathsep.isascii',
'<osl pathsep <index>>':'os.pathsep.index',
'<osl pathsep <isalpha>>':'os.pathsep.isalpha',
'<osl pathsep <isdigit>>':'os.pathsep.isdecimal',
'<osl pathsep <isidentifier>>':'os.pathsep.isidentifier',
'<osl pathsep <oslower>>':'os.pathsep.islower',
'<osl pathsep <isnumeric>>':'os.pathsep.isnumeric',
'<osl pathsep <isprintable>>':'os.pathsep.isprintable',
'<osl pathsep <isspace>>':'os.pathsep.isspace',
'<osl pathsep <istitle>>':'os.pathsep.istitle',
'<osl pathsep <isupper>>':'os.pathsep.isupper',
'<osl pathsep <join>>':'os.pathsep.join',
'<osl pathsep <ljust>>':'os.pathsep.ljust',
'<osl pathsep <lower>>':'os.pathsep.lower',
'<osl pathsep <lstrip>>':'os.pathsep.lstrip',
'<osl pathsep <mt>>':'os.pathsep.maketrans',
'<osl pathsep <partition>>':'os.pathsep.partition',
'<osl pathsep <rindex>>':'os.pathsep.rindex',
'<osl pathsep <rsplit>>':'os.pathsep.rsplit',
'<osl pathsep <removeprefix>>':'os.pathsep.removeprefix',
'<osl pathsep <removesuffix>>':'os.pathsep.removesuffix',
'<osl pathsep <replace>>':'os.pathsep.replace',
'<osl pathsep <rpartition>>':'os.pathsep.rpartition',
'<osl pathsep <__reduce__>>':'os.pathsep.__reduce__',
'<osl pathsep <__reduce_ex__>>':'os.pathsep.__reduce_ex__',
'<osl pathsep <__reversed__>>':'os.pathsep.__reversed__',
'<osl pathsep <__repr__>>':'os.pathsep.__repr__',
'<osl pathsep <__rmul__>>':'os.pathsep.__rmul__',
'<osl pathsep <split>>':'os.pathsep.split',
'<osl pathsep <strip>>':'os.pathsep.strip',
'<osl pathsep <swapcase>>':'os.pathsep.swapcase',
'<osl pathsep <startswith>>':'os.pathsep.startswith',
'<osl pathsep <splitlines>>':'os.pathsep.splitlines',
'<osl pathsep <__setattr__>>':'os.pathsep.__setattr__',
'<osl pathsep <__sizeof__>>':'os.pathsep.__sizeof__',
'<osl pathsep <__slots__>>':'os.pathsep.__slots__',
'<osl pathsep <__str__>>':'os.pathsep.__str__',
'<osl pathsep <title>>':'os.pathsep.title',
'<osl pathsep <translate>>':'os.pathsep.translate',
'<osl pathsep <upper>>':'os.pathsep.upper',
'<osl pathsep <zfill>>':'os.pathsep.zfill',
'<osl pathsep <rfind>>':'os.pathsep.rfind',
'<osl pathsep <rjust>>':'os.pathsep.rjust',
'<osl pathsep <:main_class:>>':'os.pathsep',
'<osl pardir <cap>>':'os.pardir.capitalize',
'<osl pardir <cou>>':'os.pardir.count',
'<osl pardir <cen>>':'os.pardir.center',
'<osl pardir <cas>>':'os.pardir.casefold',
'<osl pardir <class>>':'os.pardir.__class__',
'<osl pardir <con>>':'os.pardir.__contains__',
'<osl pardir <doc>>':'os.pardir.__doc__',
'<osl pardir <dict>>':'os.pardir.__dict__',
'<osl pardir <dir>>':'os.pardir.__dir__',
'<osl pardir <dela>>':'os.pardir.__delattr__',
'<osl pardir <encode>>':'os.pardir.encode',
'<osl pardir <endswith>>':'os.pardir.endswith',
'<osl pardir <expandtabs>>':'os.pardir.expandtabs',
'<osl pardir <find>>':'os.pardir.find',
'<osl pardir <format>>':'os.pardir.format',
'<osl pardir <format_M>>':'os.pardir.format_map',
'<osl pardir <__format__>>':'os.pardir.__format__',
'<osl pardir <__ge__>>':'os.pardir.__ge__',
'<osl pardir <__gt__>>':'os.pardir.__gt__',
'<osl pardir <__getitem__>>':'os.pardir.__getitem__',
'<osl pardir <geta>>':'os.pardir.__getattribute__',
'<osl pardir <hash>':'os.pardir.__hash__',
'<osl pardir <isalnum>>':'os.pardir.isalnum',
'<osl pardir <isascii>>':'os.pardir.isascii',
'<osl pardir <index>>':'os.pardir.index',
'<osl pardir <isalpha>>':'os.pardir.isalpha',
'<osl pardir <isdigit>>':'os.pardir.isdecimal',
'<osl pardir <isidentifier>>':'os.pardir.isidentifier',
'<osl pardir <oslower>>':'os.pardir.islower',
'<osl pardir <isnumeric>>':'os.pardir.isnumeric',
'<osl pardir <isprintable>>':'os.pardir.isprintable',
'<osl pardir <isspace>>':'os.pardir.isspace',
'<osl pardir <istitle>>':'os.pardir.istitle',
'<osl pardir <isupper>>':'os.pardir.isupper',
'<osl pardir <join>>':'os.pardir.join',
'<osl pardir <ljust>>':'os.pardir.ljust',
'<osl pardir <lower>>':'os.pardir.lower',
'<osl pardir <lstrip>>':'os.pardir.lstrip',
'<osl pardir <mt>>':'os.pardir.maketrans',
'<osl pardir <partition>>':'os.pardir.partition',
'<osl pardir <rindex>>':'os.pardir.rindex',
'<osl pardir <rsplit>>':'os.pardir.rsplit',
'<osl pardir <removeprefix>>':'os.pardir.removeprefix',
'<osl pardir <removesuffix>>':'os.pardir.removesuffix',
'<osl pardir <replace>>':'os.pardir.replace',
'<osl pardir <rpartition>>':'os.pardir.rpartition',
'<osl pardir <__reduce__>>':'os.pardir.__reduce__',
'<osl pardir <__reduce_ex__>>':'os.pardir.__reduce_ex__',
'<osl pardir <__reversed__>>':'os.pardir.__reversed__',
'<osl pardir <__repr__>>':'os.pardir.__repr__',
'<osl pardir <__rmul__>>':'os.pardir.__rmul__',
'<osl pardir <split>>':'os.pardir.split',
'<osl pardir <strip>>':'os.pardir.strip',
'<osl pardir <swapcase>>':'os.pardir.swapcase',
'<osl pardir <startswith>>':'os.pardir.startswith',
'<osl pardir <splitlines>>':'os.pardir.splitlines',
'<osl pardir <__setattr__>>':'os.pardir.__setattr__',
'<osl pardir <__sizeof__>>':'os.pardir.__sizeof__',
'<osl pardir <__slots__>>':'os.pardir.__slots__',
'<osl pardir <__str__>>':'os.pardir.__str__',
'<osl pardir <title>>':'os.pardir.title',
'<osl pardir <translate>>':'os.pardir.translate',
'<osl pardir <upper>>':'os.pardir.upper',
'<osl pardir <zfill>>':'os.pardir.zfill',
'<osl pardir <rfind>>':'os.pardir.rfind',
'<osl pardir <rjust>>':'os.pardir.rjust',
'<osl pardir <:main_class:>>':'os.pardir',
'<osl pipe>':'os.pipe',
'<osl plock>':'os.plock',
'<osl pathconf>':'os.pathconf',
'<osl pathconf_names>':'os.pathconf_names',
'<osl pidfd_open>':'os.pidfd_open',
'<osl pipe2>':'os.pipe2',
'<osl popen>':'os.popen',
'<osl posix_fadvise>':'os.posix_fadvise',
'<osl posix_fallocate>':'os.posix_fallocate',
'<osl posix_spawn>':'os.posix_spawn',
'<osl posix_spawnp>':'os.posix_spawnp',
'<osl read>':'os.read',
'<osl rmdir>':'os.rmdir',
'<osl readv>':'os.readv',
'<osl readlink>':'os.readlink',
'<osl register_at_fork>':'os.register_at_fork',
'<osl removedirs>':'os.removedirs',
'<osl removexattr>':'os.removexattr',
'<osl renames>':'os.renames',
'<osl replace>':'os.replace',
'<osl sep <cap>>':'os.sep.capitalize',
'<osl sep <cou>>':'os.sep.count',
'<osl sep <cen>>':'os.sep.center',
'<osl sep <cas>>':'os.sep.casefold',
'<osl sep <class>>':'os.sep.__class__',
'<osl sep <con>>':'os.sep.__contains__',
'<osl sep <doc>>':'os.sep.__doc__',
'<osl sep <dict>>':'os.sep.__dict__',
'<osl sep <dir>>':'os.sep.__dir__',
'<osl sep <dela>>':'os.sep.__delattr__',
'<osl sep <encode>>':'os.sep.encode',
'<osl sep <endswith>>':'os.sep.endswith',
'<osl sep <expandtabs>>':'os.sep.expandtabs',
'<osl sep <find>>':'os.sep.find',
'<osl sep <format>>':'os.sep.format',
'<osl sep <format_M>>':'os.sep.format_map',
'<osl sep <__format__>>':'os.sep.__format__',
'<osl sep <__ge__>>':'os.sep.__ge__',
'<osl sep <__gt__>>':'os.sep.__gt__',
'<osl sep <__getitem__>>':'os.sep.__getitem__',
'<osl sep <geta>>':'os.sep.__getattribute__',
'<osl sep <hash>':'os.sep.__hash__',
'<osl sep <isalnum>>':'os.sep.isalnum',
'<osl sep <isascii>>':'os.sep.isascii',
'<osl sep <index>>':'os.sep.index',
'<osl sep <isalpha>>':'os.sep.isalpha',
'<osl sep <isdigit>>':'os.sep.isdecimal',
'<osl sep <isidentifier>>':'os.sep.isidentifier',
'<osl sep <oslower>>':'os.sep.islower',
'<osl sep <isnumeric>>':'os.sep.isnumeric',
'<osl sep <isprintable>>':'os.sep.isprintable',
'<osl sep <isspace>>':'os.sep.isspace',
'<osl sep <istitle>>':'os.sep.istitle',
'<osl sep <isupper>>':'os.sep.isupper',
'<osl sep <join>>':'os.sep.join',
'<osl sep <ljust>>':'os.sep.ljust',
'<osl sep <lower>>':'os.sep.lower',
'<osl sep <lstrip>>':'os.sep.lstrip',
'<osl sep <mt>>':'os.sep.maketrans',
'<osl sep <partition>>':'os.sep.partition',
'<osl sep <rindex>>':'os.sep.rindex',
'<osl sep <rsplit>>':'os.sep.rsplit',
'<osl sep <removeprefix>>':'os.sep.removeprefix',
'<osl sep <removesuffix>>':'os.sep.removesuffix',
'<osl sep <replace>>':'os.sep.replace',
'<osl sep <rpartition>>':'os.sep.rpartition',
'<osl sep <__reduce__>>':'os.sep.__reduce__',
'<osl sep <__reduce_ex__>>':'os.sep.__reduce_ex__',
'<osl sep <__reversed__>>':'os.sep.__reversed__',
'<osl sep <__repr__>>':'os.sep.__repr__',
'<osl sep <__rmul__>>':'os.sep.__rmul__',
'<osl sep <split>>':'os.sep.split',
'<osl sep <strip>>':'os.sep.strip',
'<osl sep <swapcase>>':'os.sep.swapcase',
'<osl sep <startswith>>':'os.sep.startswith',
'<osl sep <splitlines>>':'os.sep.splitlines',
'<osl sep <__setattr__>>':'os.sep.__setattr__',
'<osl sep <__sizeof__>>':'os.sep.__sizeof__',
'<osl sep <__slots__>>':'os.sep.__slots__',
'<osl sep <__str__>>':'os.sep.__str__',
'<osl sep <title>>':'os.sep.title',
'<osl sep <translate>>':'os.sep.translate',
'<osl sep <upper>>':'os.sep.upper',
'<osl sep <zfill>>':'os.sep.zfill',
'<osl sep <rfind>>':'os.sep.rfind',
'<osl sep <rjust>>':'os.sep.rjust',
'<osl sep <:main_class:>>':'os.sep',
'<osl startfile>':'os.startfile',
'<osl stat>':'os.stat',
'<osl setgid>':'os.setgid',
'<osl sendfile>':'os.sendfile',
'<osl set_blocking>':'os.set_blocking',
'<osl setgroups>':'os.setgroups',
'<osl set_handle_inheritable>':'os.set_handle_inheritable',
'<osl set_inheritable>':'os.set_inheritable',
'<osl setpgid>':'os.setpgid',
'<osl setpgrp>':'os.setpgrp',
'<osl setpriority>':'os.setpriority',
'<osl setregid>':'os.setregid',
'<osl setreuid>':'os.setreuid',
'<osl setresgid>':'os.setresgid',
'<osl setresuid>':'os.setresuid',
'<osl setsid>':'os.setsid',
'<osl setuid>':'os.setuid',
'<osl setxattr>':'os.setxattr',
'<osl spawnl>':'os.spawnl',
'<osl spawnv>':'os.spawnv',
'<osl spawnle>':'os.spawnle',
'<osl spawnlp>':'os.spawnlp',
'<osl spawnlpe>':'os.spawnlpe',
'<osl spawnve>':'os.spawnve',
'<osl spawnvp>':'os.spawnvp',
'<osl spawnvpe>':'os.spawnvpe',
'<osl statvfs>':'os.statvfs',
'<osl statvfs_result>':'os.statvfs_result',
'<osl stat_result>':'os.stat_result',
'<osl strerror>':'os.strerror',
'<osl supports_fd>':'os.supports_fd',
'<osl supports_dir_fd>':'os.supports_dir_fd',
'<osl supports_follow_symlinks>':'os.supports_follow_symlinks',
'<osl supports_effective_ids>':'os.supports_effective_ids',
'<osl supports_bytes_environ>':'os.supports_bytes_environ',
'<osl sync>':'os.sync',
'<osl symlink>':'os.symlink',
'<osl sysconf>':'os.sysconf',
'<osl sysconf_names>':'os.sysconf_names',
'<osl times>':'os.times',
'<osl ttyname>':'os.ttyname',
'<osl truncate>':'os.truncate',
'<osl tcgetpgrp>':'os.tcgetpgrp',
'<osl terminal_size>':'os.terminal_size',
'<osl tcsetpgrp>':'os.tcsetpgrp',
'<osl times_result>':'os.times_result',
'<osl umask>':'os.umask',
'<osl uname>':'os.uname',
'<osl utime>':'os.utime',
'<osl unlink>':'os.unlink',
'<osl urandom>':'os.urandom',
'<osl uname_result>':'os.uname_result',
'<osl unsetenv>':'os.unsetenv',
'<osl wait>':'os.wait',
'<osl waitpid>':'os.waitpid',
'<osl walk>':'os.walk',
'<osl walkid>':'os.walkid',
'<osl walk3>':'os.walk3',
'<osl walk4>':'os.walk4',
'<osl waitid_result>':'os.waitid_result',
'<osl waitstatus_to_exitcode>':'os.waitstatus_to_exitcode',
'<osl write>':'os.write',
'<osl writevs>':'os.writevs',
'<osl error.strerror <cap>>':'os.error.strerror.capitalize',
'<osl error.strerror <cou>>':'os.error.strerror.count',
'<osl error.strerror <cen>>':'os.error.strerror.center',
'<osl error.strerror <cas>>':'os.error.strerror.casefold',
'<osl error.strerror <class>>':'os.error.strerror.__class__',
'<osl error.strerror <con>>':'os.error.strerror.__contains__',
'<osl error.strerror <doc>>':'os.error.strerror.__doc__',
'<osl error.strerror <dict>>':'os.error.strerror.__dict__',
'<osl error.strerror <dir>>':'os.error.strerror.__dir__',
'<osl error.strerror <dela>>':'os.error.strerror.__delattr__',
'<osl error.strerror <encode>>':'os.error.strerror.encode',
'<osl error.strerror <endswith>>':'os.error.strerror.endswith',
'<osl error.strerror <expandtabs>>':'os.error.strerror.expandtabs',
'<osl error.strerror <find>>':'os.error.strerror.find',
'<osl error.strerror <format>>':'os.error.strerror.format',
'<osl error.strerror <format_M>>':'os.error.strerror.format_map',
'<osl error.strerror <__format__>>':'os.error.strerror.__format__',
'<osl error.strerror <__ge__>>':'os.error.strerror.__ge__',
'<osl error.strerror <__gt__>>':'os.error.strerror.__gt__',
'<osl error.strerror <__getitem__>>':'os.error.strerror.__getitem__',
'<osl error.strerror <geta>>':'os.error.strerror.__getattribute__',
'<osl error.strerror <hash>':'os.error.strerror.__hash__',
'<osl error.strerror <isalnum>>':'os.error.strerror.isalnum',
'<osl error.strerror <isascii>>':'os.error.strerror.isascii',
'<osl error.strerror <index>>':'os.error.strerror.index',
'<osl error.strerror <isalpha>>':'os.error.strerror.isalpha',
'<osl error.strerror <isdigit>>':'os.error.strerror.isdecimal',
'<osl error.strerror <isidentifier>>':'os.error.strerror.isidentifier',
'<osl error.strerror <oslower>>':'os.error.strerror.islower',
'<osl error.strerror <isnumeric>>':'os.error.strerror.isnumeric',
'<osl error.strerror <isprintable>>':'os.error.strerror.isprintable',
'<osl error.strerror <isspace>>':'os.error.strerror.isspace',
'<osl error.strerror <istitle>>':'os.error.strerror.istitle',
'<osl error.strerror <isupper>>':'os.error.strerror.isupper',
'<osl error.strerror <join>>':'os.error.strerror.join',
'<osl error.strerror <ljust>>':'os.error.strerror.ljust',
'<osl error.strerror <lower>>':'os.error.strerror.lower',
'<osl error.strerror <lstrip>>':'os.error.strerror.lstrip',
'<osl error.strerror <mt>>':'os.error.strerror.maketrans',
'<osl error.strerror <partition>>':'os.error.strerror.partition',
'<osl error.strerror <rindex>>':'os.error.strerror.rindex',
'<osl error.strerror <rsplit>>':'os.error.strerror.rsplit',
'<osl error.strerror <removeprefix>>':'os.error.strerror.removeprefix',
'<osl error.strerror <removesuffix>>':'os.error.strerror.removesuffix',
'<osl error.strerror <replace>>':'os.error.strerror.replace',
'<osl error.strerror <rpartition>>':'os.error.strerror.rpartition',
'<osl error.strerror <__reduce__>>':'os.error.strerror.__reduce__',
'<osl error.strerror <__reduce_ex__>>':'os.error.strerror.__reduce_ex__',
'<osl error.strerror <__reversed__>>':'os.error.strerror.__reversed__',
'<osl error.strerror <__repr__>>':'os.error.strerror.__repr__',
'<osl error.strerror <__rmul__>>':'os.error.strerror.__rmul__',
'<osl error.strerror <split>>':'os.error.strerror.split',
'<osl error.strerror <strip>>':'os.error.strerror.strip',
'<osl error.strerror <swapcase>>':'os.error.strerror.swapcase',
'<osl error.strerror <startswith>>':'os.error.strerror.startswith',
'<osl error.strerror <splitlines>>':'os.error.strerror.splitlines',
'<osl error.strerror <__setattr__>>':'os.error.strerror.__setattr__',
'<osl error.strerror <__sizeof__>>':'os.error.strerror.__sizeof__',
'<osl error.strerror <__slots__>>':'os.error.strerror.__slots__',
'<osl error.strerror <__str__>>':'os.error.strerror.__str__',
'<osl error.strerror <title>>':'os.error.strerror.title',
'<osl error.strerror <translate>>':'os.error.strerror.translate',
'<osl error.strerror <upper>>':'os.error.strerror.upper',
'<osl error.strerror <zfill>>':'os.error.strerror.zfill',
'<osl error.strerror <rfind>>':'os.error.strerror.rfind',
'<osl error.strerror <rjust>>':'os.error.strerror.rjust',
'<osl error.strerror <:main_class:>>':'os.error.strerror',
'<osl error <errno>>':'os.error.errno',
'<osl error <winerror>>':'os.error.winerror',
'<osl type 2>':'import subprocess',
'<osl2 Popen>':'subprocess.Popen',
'<osl2 call>':'subprocess.call',
'<osl2 check_call>':'subprocess.check_call',
'<osl2 run>':'subprocess.run',
'<osl2 check_output>':'subprocess.check_output',
'<osl2 CalledProcessError>':'subprocess.CalledProcessError',
'<osl2 CompletedProcess>':'subprocess.CompletedProcess',
'<osl2 getoutput>':'subprocess.getoutput',
'<osl2 getstatusoutput>':'subprocess.getstatusoutput',
'<osl2 list2cmdline>':'subprocess.list2cmdline',
'<D>':'\n',
'~1':',.',
',.':'',
}